# 2 Layer Neural Network

## needed imports

In [1]:
from numpy import (
    array, # to make matrix operations easy
    dot, # matrix multiplication func
    exp # for sigmoid func
)
from numpy.random import (
    random, # for random number generation
    seed # for getting random number each time
)

## Class for Layer

In [2]:
class NeuronLayer():
    """ 
        Each layer contains many neurons and each neuron can accept any inputs.
        But each neuron can produce only 1 output, which will be fed into next layer
    """

    def __init__(
        self, 
        number_of_neurons, # no.of neurons per each layer
        number_of_inputs_per_neuron # no.of inputs each neuron should work with
    ):
        # taking random weights for each neuron in current layer (weights per neuron * no of neurons)
        self.synaptic_weights = 2 * random((number_of_inputs_per_neuron, number_of_neurons)) - 1

## Class for Network

In [3]:
class NeuralNetwork():
    """
        The complete network, with multiple layers configured
        This takes inputs to the 1st layer and gives output form the last layer
    """

    def __init__(
        self, 
        layer1, # Starting point of Neural Network. entry point for data
        layer2 # Ending point of Neural Network. this returns predictions
    ):
        self.layer1 = layer1
        self.layer2 = layer2

    def __sigmoid(self, x):
        # sigmoid func, used as a Perceptron
        return 1 / (1 + exp(-x))

    def __sigmoid_derivative(self, x):
        # derivative of sigmoid func, used to alter weights
        return x * (1 - x)

    def train(
        self, 
        training_set_inputs, # independent variables (x)
        training_set_outputs, # dependent variables (y)
        number_of_training_iterations # iterations for gradiant descent
    ):
        for _ in range(number_of_training_iterations):

            # output from both layers are calculated. ideally, layer 2's output should match with (y)
            output_from_layer_1, output_from_layer_2 = self.predict(training_set_inputs)

            # deviation from (y) to layer 2 is calculated to alter weights of layer 2
            layer2_error = training_set_outputs - output_from_layer_2
            layer2_delta = layer2_error * self.__sigmoid_derivative(output_from_layer_2)

            # deviation from new layer 2 to layer 1 is calculated to alter weights of layer 1
            layer1_error = layer2_delta.dot(self.layer2.synaptic_weights.T)
            layer1_delta = layer1_error * self.__sigmoid_derivative(output_from_layer_1)

            # altering each layer slightly at a time, based on amount of deviation each had
            layer1_adjustment = training_set_inputs.T.dot(layer1_delta)
            layer2_adjustment = output_from_layer_1.T.dot(layer2_delta)

            self.layer1.synaptic_weights += layer1_adjustment
            self.layer2.synaptic_weights += layer2_adjustment

    def predict(self, inputs):
        """
            This calculates sigmoid at layer 1 & gives its results to layer 2 and returns its results
        """

        # input variables are multiplied with weights & calculated sigmoid
        output_from_layer1 = self.__sigmoid(dot(inputs, self.layer1.synaptic_weights))

        # layer 1 output is multiplied with layer 2 weights and calculated sigmoid for them as well
        output_from_layer2 = self.__sigmoid(dot(output_from_layer1, self.layer2.synaptic_weights))

        # returning both layer's output to optimize weights at each layer
        return output_from_layer1, output_from_layer2

    def print_weights(self):
        """ prints weights of both layers """

        print("Layer 1 (4 neurons, each with 3 inputs):")
        print(self.layer1.synaptic_weights)

        print("Layer 2 (1 neuron, with 4 inputs):")
        print(self.layer2.synaptic_weights)

## Usage of Above Code

In [4]:
if __name__ == "__main__":
    # seeding random variable to get same random values each time
    seed(1)

    # defining layers with no.of neurons and their no.of inputs
    layer1 = NeuronLayer(number_of_neurons=4, number_of_inputs_per_neuron=3)
    layer2 = NeuronLayer(number_of_neurons=1, number_of_inputs_per_neuron=4)

    # defining neural network with defined layers
    neural_network = NeuralNetwork(layer1=layer1, layer2=layer2)

    # printing initial weights for each layer
    print("Stage 1) Random starting synaptic weights:")
    neural_network.print_weights()

    # independent variables (x)
    training_set_inputs = array([[0, 0, 1],
                                 [0, 1, 1],
                                 [1, 0, 1],
                                 [0, 1, 0],
                                 [1, 0, 0],
                                 [1, 1, 1],
                                 [0, 0, 0]])
    # dependent variables (y)
    training_set_outputs = array([[0],
                                  [1],
                                  [1],
                                  [1],
                                  [1],
                                  [0],
                                  [0]])

    # training defined neural network with (x) -> (Y) for 60000 iterations
    neural_network.train(training_set_inputs, training_set_outputs, 60000)

    # printing final weights for each layer after training
    print("Stage 2) New synaptic weights after training: ")
    neural_network.print_weights()

    # printing predictions for untrained parameters
    print("Stage 3) Considering a new situation [1, 1, 0] -> ?: ")
    hidden_state, output = neural_network.predict(array([1, 1, 0]))

    print(output)

Stage 1) Random starting synaptic weights:
Layer 1 (4 neurons, each with 3 inputs):
[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]
Layer 2 (1 neuron, with 4 inputs):
[[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]]
Stage 2) New synaptic weights after training: 
Layer 1 (4 neurons, each with 3 inputs):
[[ 0.3122465   4.57704063 -6.15329916 -8.75834924]
 [ 0.19676933 -8.74975548 -6.1638187   4.40720501]
 [-0.03327074 -0.58272995  0.08319184 -0.39787635]]
Layer 2 (1 neuron, with 4 inputs):
[[ -8.18850925]
 [ 10.13210706]
 [-21.33532796]
 [  9.90935111]]
Stage 3) Considering a new situation [1, 1, 0] -> ?: 
[0.0078876]
